/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DriveItemsImport } from './routes/drive-items'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const DriveItemsRoute = DriveItemsImport.update({
  path: '/drive-items',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/drive-items': {
      id: '/drive-items'
      path: '/drive-items'
      fullPath: '/drive-items'
      preLoaderRoute: typeof DriveItemsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ IndexRoute, DriveItemsRoute })

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/drive-items"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/drive-items": {
      "filePath": "drive-items.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
