/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CheckboxAnimationImport } from './routes/checkbox-animation'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const CheckboxAnimationRoute = CheckboxAnimationImport.update({
  path: '/checkbox-animation',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/checkbox-animation': {
      id: '/checkbox-animation'
      path: '/checkbox-animation'
      fullPath: '/checkbox-animation'
      preLoaderRoute: typeof CheckboxAnimationImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  CheckboxAnimationRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/checkbox-animation"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/checkbox-animation": {
      "filePath": "checkbox-animation.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
